[package]
name = "decode-userop-dan"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-core = "0.7.7"
alloy-sol-types = "0.7.7"
ethabi = "18.0.0"
ethereum-types = "0.14.1"
hex = "0.4.3"
hex-literal = "0.4.1"
proptest = "1.5.0"
